### ISSUE TITLE
Feature: Redis AsyncAPI security option

### ISSUE THREAD

**Issue by Lancetnik** [airtai/faststream#1020]

**Comment by sternakt** [comment]
When initializing Redis, the `Redis` class redirects the ssl kwargs to the `SSLConnection` class: [code](https://github.com/redis/redis-py/blob/master/redis/client.py#L292-L309).

The `SSLConnection` class then internally handles the creation of ssl context creation internally: [code](https://github.com/redis/redis-py/blob/master/redis/connection.py#L730-L746)

In our case, our security objects already have the concrete SSL context which we cannot "disassemble" into params for Redis.
Possible solutions could be: 

1. Monkey Patching:
One approach is to monkey patch the `SSLConnection` class to use our SSL context.
Bad idea, in my opinion, but only real one I have ATM
2. Feature Request or Fork:
We could try to implement direct ssl context passing at redis side, I'm not sure if this change will be accepted
3. We could redesign our security objects to include the Redis ssl params, but this beats the whole idea of creating the security objects in the first place (We wanted to have them so that we could simplify the security configuration across all brokers and not have to include special params).


@Lancetnik @davorrunje What are your thoughts?

**Comment by Lancetnik** [comment]
4) we can create a Redis-specific security object, but parse it to AsyncAPI like our regular one
5) the best decision I think - we can replace original "connection_class" [here](https://github.com/redis/redis-py/blob/master/redis/asyncio/connection.py#L940) to use our own RedisSSLConnection class with overrided [`_connect` method](https://github.com/redis/redis-py/blob/master/redis/connection.py#L727)
