### ISSUE TITLE
Bug: Not compatible with fastapi.Depends

### ISSUE THREAD

**Issue by WATUNeed** [airtai/faststream#1216]
**Describe the bug**
The bug consists of two things:

1) When importing Depends from Fastapi and FastStream together, they overwrite each other.
2) When using Depends from fastapi for Faststream, an error occurs. And vice versa.

**How to reproduce**
Include source code:

```python
import fastapi
import fast_depends


async def _get_session() -> Generator[AsyncSession, None, None]:
    session = Session()
    try:
        await session.begin()
        yield session
        await session.commit()
    except Exception as e:
        await session.rollback()
        raise e
    finally:
        await session.close()

get_session_fastapi = Annotated[AsyncSession, fastapi.Depends(_get_session, use_cache=True)]
get_session_faststream = Annotated[AsyncSession, fast_depends.Depends(_get_session, use_cache=True)]
```

You should always remember where you are importing Depends from.
It is impossible to use one function for two frameworks together.

The ideal solution is full compatibility with Depends from Fastapi.

**Comment by Lancetnik** [comment]
@WATUNeed thank for the Issue, but we can't use **FastAPI** Depends as a basic **FastStream** dependencies.
**FastStream** is a standalone framework and it totally independent from **FastAPI**.
**FastStream-FastAPI** is just a compatibility layer to make **FastStream** much suitable in **FastAPI** applications. But it is not core part of the framework.

So, why we should use **FastAPI** Depends as a core DI system if we are not using it as a core dependency? Should we use [taskiq-depends](https://github.com/taskiq-python/taskiq-dependencies) or [Dependency injector](https://github.com/ets-labs/python-dependency-injector) the same way?

Using **FastStream** you should decide at first, that way you want to use it: as a **FastAPI** plugin or standalone app?
Basing on this decidion you will use totally difference imports everywhere (router instead of broker, context from fastapi instead of regular one, FastAPI Depends instead of native Depends, etc). So, I can't image the case, then you 

> You should always remember where you are importing Depends from.

In regular case - regular Depends, in FastAPI case - FastAPI ones.

But, if you want to support both of them (for some strange reason), you can use them both in the same time

```python
get_session = Annotated[
    AsyncSession,
    fastapi.Depends(_get_session, use_cache=True),
    fast_depends.Depends(_get_session, use_cache=True),
]
```

This code works fine in **FastAPI** and regular **FastStream** cases both.
