### ISSUE TITLE
Add blog section to docs

### ISSUE THREAD

**Issue by kumaranvpl** [airtai/faststream#827]
https://squidfunk.github.io/mkdocs-material/plugins/blog/

https://dev.to/airtai/how-we-deprecated-two-successful-projects-and-joined-forces-to-create-an-even-more-successful-one-3lon

**Comment by kumaranvpl** [comment]
I am pausing my efforts. Material mkdocs' blog plugin is right now incompatible with mkdocs-static-i18n as one can see in the following issues

https://github.com/ultrabug/mkdocs-static-i18n/issues/263
https://github.com/ultrabug/mkdocs-static-i18n/issues/246

For now I will push my progress. Once a new version with fixes is out then I can resume.

**Comment by Lancetnik** [comment]
Wait for the PR https://github.com/ultrabug/mkdocs-static-i18n/pull/268

**Comment by Lancetnik** [comment]
I think, that is not required. Probably, we can remove i18n as well due we have no resources on alternative languages

**Comment by kumaranvpl** [comment]
@Lancetnik If we remove `i18n` plugin then adding a blog section is easier. 
Maybe we could move the [HowTo](https://faststream.airt.ai/latest/howto/kafka/) sections to blog so users would be more willing to contribute.

**Comment by Lancetnik** [comment]
I don't think, that we should create blog section at all. Airt blog should be concentrated in one place instead of separated blogs for each tool. Also, How-to section is not in a blog format, it is a notices with ready-to-use code examples with explanation, I suggest to maintain them right in the documentation, that should be much helpful there.
